version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/atm-docker

hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_application.sh
      runas: ec2-user
